name: Apply

on:
  push:
    paths:
      - 'pages/*'

jobs:

  apply:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Cache python modules
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        yarn --dev
        python -m pip install -r requirements.txt

    - name: Lint
      run: yarn run lint

    - name: Apply
      if: github.ref == 'refs/heads/master' && success()
      env:
        FEMIWIKI_BOT_PASSWORD: ${{ secrets.FEMIWIKI_BOT_PASSWORD }}
      run: |
        git config --global core.quotepath false
        python apply.py $(git diff-tree --no-commit-id --name-only -r "${GITHUB_SHA}")
