name: Apply

on:
  push:
    branches:
      - master
    paths:
      - 'pages/*'
      - 'gadgets/**'

jobs:

  apply:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Cache python modules
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        yarn --dev
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt

    - name: Lint
      run: |
        yarn run lint
        flake8

    - name: Unit test (Python)
      run: pytest


    - name: Download last applied commit id
      continue-on-error: true
      uses: actions/download-artifact@v1
      with:
        name: artifact

    - name: Apply
      if: github.ref == 'refs/heads/master' && success()
      env:
        FEMIWIKI_BOT_PASSWORD: ${{ secrets.FEMIWIKI_BOT_PASSWORD }}
      run: |
        git config --global core.quotepath false
        export PREVIOUS=$(cat .last-applied-commit 2>/dev/null)
        python apply.py "$PREVIOUS"

    - name: Save last applied commit id
      if: success()
      run: |
        echo $GITHUB_SHA > .last-applied-commit

    - name: Upload last applied commit id
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: .last-applied-commit
