name: Apply

on:
  push:

jobs:

  apply:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v7
      with:
        fetch-depth: 30

    - uses: actions/setup-node@v4

    - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0

    - name: Install dependencies
      run: |
        npm ci
        uv sync --locked

    - name: Lint
      run: |
        npm run lint
        uv run --locked flake8

    - name: Unit test (Python)
      run: uv run --locked pytest

    - name: Apply
      if: github.ref == 'refs/heads/main' && success()
      env:
        FEMIWIKI_BOT_PASSWORD: ${{ secrets.FEMIWIKI_BOT_PASSWORD }}
      run: |
        git config --global core.quotepath false
        uv run --locked python apply.py
