on:
  push:
    paths:
      - 'pages/*'
      - 'gadgets/**'
      - 'lua/**'
  pull_request:
    paths:
      - 'pages/*'
      - 'gadgets/**'
      - 'lua/**'

jobs:
  gadget-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
