on:
  push:
    paths:
      - 'pages/*'
      - 'gadgets/**'
      - 'lua/**'
  pull_request:
    paths:
      - 'pages/*'
      - 'gadgets/**'
      - 'lua/**'

jobs:
  gadget-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --dev

      - name: Lint
        run: yarn run lint
